### ISSUE TITLE
Transaction failure on close channel

### ISSUE THREAD

**Issue by matthiasgeihs** [perun-network/perun-eth-demo#24] opened 2020-08-06 06:25 UTC
when running the demo with ganache-cli --block-time 5, the following warning occurs at bob when alice closes the channel:
>WARN[0030] TX failed; error determining reason: CallContract: VM Exception while processing transaction: revert channel already concluded 
WARN[0030] Calling conclude(Final) failed, waiting for event anyways...  account=0xA298Fc05bccff341f340a11FffA30567a00e651f

**Comment by ggwpez** [comment] 2020-08-06 14:07
This is not a bug, but it looks a bit weird. Alice and Bob call `settle` in the same block, which results in one of their TX being reverted.  
This can be circumvented by having a wait (like it is right now but only works for `--block-time 1`) or fixing it in *go-perun*.

**Comment by ggwpez** [comment] 2021-11-09 14:22
This should be fixed with the [v0.6.0 update](https://github.com/perun-network/perun-eth-demo/commit/ccb02a0334a03ba228fe28ccc7daf6f9d6763788#diff-0ddd5848cf621d5d0da61c8a73194720d2651ca70d9a776a3c3908020df6222cR343) by using the `secondary` flag.

**Closed as completed by ggwpez** 2021-11-09 14:22 UTC
